### ISSUE TITLE
question about paper

### ISSUE THREAD

**Issue by czy341181** [charlesCXK/TorchSemiSeg#3]
Does the network generate labels for all pixels of each image to supervise another network during training? (in GCT some pixel that higher than a certain threshold is selected). 

In the early stage of network training, the labels predicted by poor performance at the beginning are inaccurate, and is it reasonable to use the wrong labels as supervisory information for another network?

**Comment by charlesCXK** [comment]
Hi, we use all the pixels as the target for the other network during training, without any threshold selection. This makes our approach simple and clean.

In the early stage of training, there must exist some pixels with wrong predictions in both networks. Let's consider these situations (two columns in each row means whether the prediction of each network is correct):

```
(1) Correct, Correct
(2) Correct, Wrong
(3) Wrong, Correct
(4) Wrong, Wrong
```

In (1)(3), the target is correct, so the prediction is supervised with the correct signal.
In (4), both the prediction and the target are wrong, but the prediction will be punished. So it is hard to say whether it is harmful or not.
In (2), the supervision signal is wrong, which may be harmful.

I think our CPS works well because the advantages outweigh the disadvantages that exist in these four situations. One may design an algorithm to suppress the wrong supervision signal in the early training, which may further improve CPS.

**Comment by czy341181** [comment]
Thanks for your patient reply! The method is very simple and effective.

By the way, If it is simply set the threshold of segmentation score of networks output, above a certain threshold as a pseudo label, like GCT. Does it work? Have you done any experiments like this?

**Comment by charlesCXK** [comment]
We haven't conducted experiments like this. Since the code and data are released, one could try different strategies themselves~
